services:
  app:
    build: .
    container_name: app-1
    env_file:
      - .env
    environment:
      - DB_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    container_name: redis-1
    ports:
      - "6379:6379"
  db:
    image: postgres:17
    container_name: postgres-1
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
